# -*- coding: utf-8 -*-
"""Generacion-de-codigos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13s1KYlDhFSOBy-WHS__IPhqyWqETWgS9
"""

# ==============================================================================
# PASO 1: INSTALACIÓN, IMPORTACIÓN Y AUTENTICACIÓN
# ==============================================================================
!pip install gspread google-auth-oauthlib pandas -q

import pandas as pd
import gspread
from google.auth import default
from google.colab import auth
import random

print("Autenticando tu cuenta de Google...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
print("¡Autenticación exitosa!")

# ==============================================================================
# PASO 2: CONFIGURACIÓN Y LECTURA DEL GOOGLE SHEETS
# ==============================================================================
SHEET_URL = "https://docs.google.com/" #Agregar pagina de google sheets!!!!!!!!!!
NOMBRE_DE_LA_COLUMNA = "Codigos" # Solo necesitamos el nombre de la columna

df_original = pd.DataFrame()
worksheet = None

try:
    print(f"\nAbriendo el archivo desde la URL...")
    spreadsheet = gc.open_by_url(SHEET_URL)

    # --- ¡CORRECCIÓN DEFINITIVA! ---
    # En lugar de buscar por nombre "Hoja1", abrimos la PRIMERA PESTAÑA disponible.
    # Esto evita problemas de idioma ("Sheet1", "Hoja 1", etc.)
    print("Accediendo a la primera pestaña del archivo...")
    worksheet = spreadsheet.sheet1

    print("Lectura de datos exitosa. Obteniendo registros...")
    data = worksheet.get_all_records()
    df_original = pd.DataFrame(data)

    if NOMBRE_DE_LA_COLUMNA in df_original.columns:
        df_original[NOMBRE_DE_LA_COLUMNA] = df_original[NOMBRE_DE_LA_COLUMNA].astype(str)
        existing_codes = set(df_original[NOMBRE_DE_LA_COLUMNA].unique())
        print(f"Se encontraron {len(existing_codes)} códigos únicos existentes.")
    else:
        print(f"Error: La columna '{NOMBRE_DE_LA_COLUMNA}' no se encontró en la hoja.")
        df_original = pd.DataFrame() # Reseteamos si la columna no existe

except Exception as e:
    print(f"Ha ocurrido un error detallado al leer el archivo: {e}")

# ==============================================================================
#  GENERACIÓN INCREMENTAL DE CÓDIGOS
# ==============================================================================
# La condición 'worksheet is not None' asegura que esta parte solo se ejecute si la lectura fue exitosa.
if not df_original.empty and worksheet is not None:
    CANTIDAD_PB_A_GENERAR = 5
    CANTIDAD_CB_A_GENERAR = 5

    new_codes = []
    print(f"\n--- Iniciando Generación Incremental ---")

    # --- Proceso para códigos 'PB' ---
    df_pb = df_original[df_original[NOMBRE_DE_LA_COLUMNA].str.startswith('PB', na=False)]

    if not df_pb.empty:
        max_pb_num = df_pb[NOMBRE_DE_LA_COLUMNA].str[2:].astype(int).max()
    else:
        max_pb_num = -1
        print("No se encontraron códigos 'PB' existentes. Se comenzará la secuencia desde 000000.")

    print(f"El último código 'PB' encontrado es: PB{max_pb_num:06d}")

    for i in range(CANTIDAD_PB_A_GENERAR):
        next_pb_num = max_pb_num + 1 + i
        new_pb_code = f"PB{next_pb_num:06d}"
        new_codes.append(new_pb_code)

    # --- Proceso para códigos 'CB' ---
    df_cb = df_original[df_original[NOMBRE_DE_LA_COLUMNA].str.startswith('CB', na=False)]

    if not df_cb.empty:
        max_cb_num = df_cb[NOMBRE_DE_LA_COLUMNA].str[2:].astype(int).max()
    else:
        max_cb_num = -1
        print("No se encontraron códigos 'CB' existentes. Se comenzará la secuencia desde 000000.")

    print(f"El último código 'CB' encontrado es: CB{max_cb_num:06d}")

    for i in range(CANTIDAD_CB_A_GENERAR):
        next_cb_num = max_cb_num + 1 + i
        new_cb_code = f"CB{next_cb_num:06d}"
        new_codes.append(new_cb_code)

    print("\n--- ¡Códigos Incrementales Generados Exitosamente! ---")
    new_codes_sorted = sorted(new_codes)
    for codigo in new_codes_sorted:
        print(codigo)

    # Guardar los nuevos códigos de vuelta en la hoja de Google Sheets
    if new_codes_sorted:
        print("\nGuardando los nuevos códigos en la hoja de cálculo...")
        rows_to_add = [[code] for code in new_codes_sorted]
        worksheet.append_rows(rows_to_add, value_input_option='USER_ENTERED')
        print(f"¡Éxito! Se han añadido {len(rows_to_add)} nuevos códigos a tu Google Sheet.")
    else:
        print("\nNo se generaron nuevos códigos para guardar.")

else:
    print("\nNo se generaron códigos porque el DataFrame original está vacío o la hoja no se pudo cargar.")